services:
  app:
    build: .
    container_name: shortsmaker-frontend-release
    ports:
      - "54545:80"
    restart: always
    networks:
      - shortsmaker-network

networks:
  shortsmaker-network:
    external: true
    name: app_shortsmaker-network
