services:
  devcontainer:
    container_name: shortsmaker-frontend-devcontainer
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces/shortsmaker:cache
      - ${HOME}/.ssh:/home/node/.ssh:ro
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    environment:
      - TZ=America/Sao_Paulo
      - GIT_SSH_COMMAND=ssh -i /home/node/.ssh/lsilvpin_id_rsa
    command: sleep infinity
    networks:
      - app_shortsmaker-network

networks:
  app_shortsmaker-network:
    external: true
